### ISSUE TITLE
How to use this api?

### ISSUE THREAD

**Issue by vishnudevk** [vitalidze/chromecast-java-api-v2#11]
Is it receiver api?
Can you please put some example app/code to use this api in an android app?

**Comment by vitalidze** [comment]
This is a sender API. I am not an android developer, so I cannot put an example app here. The code to call API methods should be same as provided in current examples.

I think it's better to use [official android sdk for chromecast](https://developers.google.com/cast/docs/android_sender) instead of this library. The goal of this library was to write senders for desktop/server applications.
