### ISSUE TITLE
Ability to receive spontaneous events from ChromeCasts

### ISSUE THREAD

**Issue by haku** [vitalidze/chromecast-java-api-v2#19]
When the ChromeCast finishes playing a file it sends a [spontaneous event](https://developers.google.com/cast/docs/reference/messages#MediaMess) back to the requester to say that playback has finished.  Unfortunately as this response is not associated with a particular request (`requestId=0`), it is discarded.

For example:
```
<-- {"type":"MEDIA_STATUS","status":[{"mediaSessionId":1,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"currentItemId":1,"idleReason":"FINISHED"}],"requestId":0}

<-- {"requestId":0,"status":{"applications":[{"appId":"CC1AD845","displayName":"Default Media Receiver","namespaces":[{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"CF2E435E-B753-4621-94A4-53DBFDAC15C3","statusText":"Ready To Cast","transportId":"web-0"}],"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}
```

The `mediaSessionId` matches the value in the response to the LOAD request, e.g.
```
--> {"type":"LOAD","requestId":95,"sessionId":"CF2E435E-B753-4621-94A4-53DBFDAC15C3","media":{"contentId":"http://192.168.1.4:29085/media","contentType":"audio/mpeg"},"autoplay":true,"currentTime":0.0,"customData":{"payload":{"title:":"title goes here","thumb":"art"}}}

<-- {"type":"MEDIA_STATUS","status":[{"mediaSessionId":1,"playbackRate":1,"playerState":"BUFFERING","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"media":{"contentId":"http://192.168.1.4:29085/media","contentType":"audio/mpeg","duration":36.306225},"currentItemId":1,"items":[{"itemId":1,"media":{"contentId":"http://192.168.1.4:29085/media","contentType":"audio/mpeg","duration":36.306225},"autoplay":true,"customData":{"payload":{"title:":"title goes here","thumb":"art"}}}],"repeatMode":"REPEAT_OFF"}],"requestId":95}
```
So perhaps calling `ChromeCast.load()` could also take a callback parameter to receive all events for that `mediaSessionId`?
Though not all spontaneous messages have `mediaSessionId`, so would still need some other mechanism to react to those.

For reference, currently these events get as far as here before being discarded:
https://github.com/vitalidze/chromecast-java-api-v2/blob/master/src/main/java/su/litvak/chromecast/api/v2/Channel.java#L137

If you are busy I am happy to implement this myself and raise a PR.

**Comment by vitalidze** [comment]
You are right. I am very busy until the new year. So probably it's better to implement it by yourself and send me a PR.

Regarding implementation, I would stick with an observer pattern. Each `ChromeCast` object can have a list of spontaneous event listeners. Then when message with `requiestId == 0` is received instead of discarding it will just notify all listeners about the event. I think the event should contain parsed response (if possible) or the `Map<String, Object>` with some generic response data. For example, for this message

````json
<-- {"type":"MEDIA_STATUS","status":[{"mediaSessionId":1,"playbackRate":1,"playerState":"IDLE","currentTime":0,"supportedMediaCommands":15,"volume":{"level":1,"muted":false},"currentItemId":1,"idleReason":"FINISHED"}],"requestId":0}
````

It will contain the `MediaStatus` result. Then `load` method of the `ChromeCast` class should return the `MediaStatus`, which will have a `mediaSessionId`. Then in consumer code you can easily match events by that media session identifier.

As for the callback, my big doubt is that it is not clear when you should unsubscribe from such events. I mean if you will subscribe on every call of `load` then probably at some point of time there could be a memory leak of such listeners. If you know when to unsubscribe, then probably it's better to implement such callback on a higher level, i.e. in the `CrhomeCast` class, which will also use same spontaneous events listening mechanisms.

**Comment by vitalidze** [comment]
Closing it since #20 was merged today. Re-open if necessary.
