### ISSUE TITLE
Higher quality streaming

### ISSUE THREAD

**Issue by MCMastery** [vitalidze/chromecast-java-api-v2#36]
I know this project does all you need it to do, but I was wondering what can be done to improve the quality of streaming. I am writing an audio / visualizer streaming program with this, and when I play a song, it sounds sort of crackly (when I play it without ChromeCast it sounds fine). Thank you

**Comment by vitalidze** [comment]
Actually I have no idea. From my understanding you should have a server, which serves audio stream, maybe there is some issue with such server, or maybe you should play with audio codecs. Also I think it's better to ask on the google cast community pages on [google plus](https://plus.google.com/communities/115742157569103585450) or in [google groups](https://productforums.google.com/forum/#!forum/chromecast). This project is more about a "sender" rather than a streaming server. 

Also I know that [UniversalMediaServer](http://www.universalmediaserver.com/) supports casting video (and probably audio) to the ChromeCast, using my library. Maybe it's worth to check out how it works with your audio file too.

**Comment by MCMastery** [comment]
Ok, thank you
