### ISSUE TITLE
Unable to load media

### ISSUE THREAD

**Issue by rahmnathan** [vitalidze/chromecast-java-api-v2#43]
I'm able to start up the default receiver application (CC1AD845) just fine, but when I go to load a media file I get "su.litvak.chromecast.api.v2.ChromeCastException: Unable to load media". I've casted this file with castnow from the same machine without issue, so I don't think it's a problem with the source file. 

This is probably a stupid question, but there isn't exactly a ton of documentation here. Any advice would be greatly appreciated. Thanks!

**Comment by vitalidze** [comment]
Are you sure you are using correct URL to cast your media? Looks like you don't understand how the chromecast works. I think that `castnow` starts some kind of built-in web server, which streams you local files, then it just sends an URL to the chromecast. 

This library does not have any built-in web server, instead of this it allows you to send commands to the chromecast. If you need to cast some local files you will have to provide them in a way that chromecast device can access them.

**Comment by otaviodecampos** [comment]
I tested yesterday and worked fine. When you send media to chromecast, the url must point to an http server. (local or remote)

**Comment by rahmnathan** [comment]
@vitalidze @otaviodecampos Thanks for the information! I had no idea that I had to do that. It appears setting up an NFS server would be what I want to do?

**Comment by otaviodecampos** [comment]
You can serve media file to chromecast on many ways, on different languages. The important is:

- The file must be accessible by http address, example: http://192.168.1.10/media/file
- The file must have a format supported by chromecast: https://developers.google.com/cast/docs/media

This project https://github.com/aruld/jersey-streaming uses Jersey to serve a media file to streaming with REST. You can use as example.
