### ISSUE TITLE
Determine MIME type when not provide

### ISSUE THREAD

**Issue by lolodomo** [vitalidze/chromecast-java-api-v2#67]
As discussed here https://github.com/openhab/openhab2-addons/issues/1628 we discovered that load is failing if MIME type is not provided to the load method. Could it be possible to update the code to try to automatically determine the MIME type when not provided ?
As you can see, @tavalin proposed a code to do that.

**Comment by maggu2810** [comment]
> As you can see, @tavalin proposed a code to do that.

Didn't see it

**Comment by tavalin** [comment]
https://github.com/openhab/openhab2-addons/pull/1844

**Comment by vitalidze** [comment]
From my point of view this is out of scope of the library. The requirement to provide MIME type comes from the Google Cast. But anyway, I think it will be useful to have such functionality since playback of some media is the core function. I will think about it, most probably it will be included. Thank you for suggesting.

**Comment by mrothenbuecher** [comment]
[Tika](https://tika.apache.org/0.10/api/org/apache/tika/Tika.html) could solve this problem quite fast

**Comment by vitalidze** [comment]
FYI I have released 0.10.0 today with the automatic detection of MIME type if it is not specified explicitly. It is already available in maven central.
